#!/bin/sh

usage () {
  cat<<EOF
Usage: ./install <install-to-path>
  See INSTALL.md for instructions.
EOF
}

failure_and_die () {
  echo "UPC++ Installation failed. Please report the ENTIRE log above to: upcxx@googlegroups.com" >&2
  exit 1
}

big_warning () {
  cat<<EOF
*******
WARNING: This install script exists only to support legacy usage.
WARNING: New features in UPC++ may not be supported via this interface.
WARNING: Users are encouraged to use the 'configure; make; make install'
WARNING: steps as documented in INSTALL.md.
*******
EOF
}

big_warning

if test "$1" = "-h" || test "$1" = "--help"; then
  usage
  exit 0
elif test "$#" -eq 1; then
  install_to="$1"
else
  >&2 usage
  exit 1
fi

./configure --prefix="${install_to}" || failure_and_die
${UPCXX_MAKE:-${GMAKE:-make} -j8} install || failure_and_die

echo 'UPC++ successfully installed'
big_warning
